name: DeployToVPS

on:
  push:
    branches:
      - flask-api  # Monitora a branch flask-api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
        with:
          pre-deploy: |
            echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" | sudo tee -a /etc/environment > /dev/null
            if ! grep -q "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" /etc/environment; then
              echo "Erro: GOOGLE_API_KEY não foi adicionada ao /etc/environment."
              exit 1
            fi
            echo "Variável GOOGLE_API_KEY adicionada com sucesso ao /etc/environment."

          post-deploy: |
            cd ${{ secrets.REMOTE_TARGET }}
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            fi
            echo "Deploy concluído com sucesso!"
