name: DeployToVPS
on:
  push:
    branches:
      - flask-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }} # Chave privada SSH
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }} # IP da máquina
          REMOTE_USER: ${{ secrets.REMOTE_USER }} # Nome do usuário da máquina
          TARGET: ${{ secrets.REMOTE_TARGET }} # Pasta em que vão ficar os arquivos do repositório
        with:
          ssh-deploy-args: '--exclude=".env"' # Ignora o arquivo .env durante o deploy
          pre-deploy: |
            echo "Iniciando o deploy..."

          post-deploy: |
            # Navega até a pasta de destino
            cd ${{ secrets.REMOTE_TARGET }}

            # Instala dependências do projeto (se necessário)
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            fi

            echo "Deploy concluído com sucesso!"
